"""enclosure images for table

Revision ID: e7f4dcea3c74
Revises: 677815332c24
Create Date: 2023-03-29 12:16:40.754396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f4dcea3c74'
down_revision = '677815332c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enclosures', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
